"""Hebed Proxy engine launcher.

Frozen entry point (PyInstaller) that runs mitmdump with the PII redaction
addon. The launcher is bundled inside the installer so a fresh machine needs
NO Python, mitmproxy, or Presidio installed — everything ships with the app.

The addon source (pii_redact.py) and its spaCy config (spacy_en_fr_de_it.yaml)
are NOT shipped as files. They are embedded as base64 constants in
embedded_addon.py, compiled into the PYZ bytecode archive. At startup the
launcher extracts them to a per-process temp dir, rewrites the -s argument
to point at the extracted addon, and deletes the temp dir on exit.

Arguments are forwarded verbatim to mitmdump, e.g.:
    hebed-proxy-engine --listen-port 8080 -s <ignored addon path>

Environment:
    PII_LOG_DIR   log directory for pii_events.log / files.log / prompts.log
    PII_REDACT_FILES=1  also modify uploaded file bodies
    PII_DEBUG=1         dump raw request bodies
"""

import atexit
import base64
import os
import shutil
import sys
import tempfile

import embedded_addon  # generated by build_engine.py


def _prepare_addon(argv):
    """Extract the embedded addon to a temp dir and point -s at it.

    mitmproxy's script loader (SourceFileLoader) requires a real file path,
    so the addon cannot be imported from memory directly. We write it to a
    per-process temp dir; the dir is removed when the engine exits.
    """
    # Clean up stale extraction dirs from previous runs. Rust kills the engine
    # with TerminateProcess on toggle-off, which skips Python's atexit, so a
    # hard-killed engine leaves its temp dir behind. Only one engine runs at
    # a time, so deleting all leftover hebed-addon-* dirs is safe.
    try:
        stale_root = tempfile.gettempdir()
        for entry in os.listdir(stale_root):
            if entry.startswith("hebed-addon-"):
                shutil.rmtree(os.path.join(stale_root, entry), ignore_errors=True)
    except Exception:
        pass

    tmp = tempfile.mkdtemp(prefix="hebed-addon-")
    addon_path = os.path.join(tmp, "pii_redact.py")
    config_path = os.path.join(tmp, "spacy_en_fr_de_it.yaml")

    with open(addon_path, "wb") as f:
        f.write(base64.b64decode(embedded_addon.ADDON_B64))
    with open(config_path, "wb") as f:
        f.write(base64.b64decode(embedded_addon.CONFIG_B64))

    # Rewrite the -s argument: mitmproxy needs the file path of the extracted
    # addon. Replace the first -s <value> pair regardless of what was passed.
    out = []
    i = 0
    replaced = False
    while i < len(argv):
        if argv[i] == "-s" and i + 1 < len(argv) and not replaced:
            out.append("-s")
            out.append(addon_path)
            i += 2
            replaced = True
            continue
        out.append(argv[i])
        i += 1

    # Defensive: if no -s was present, append one pointing at the addon.
    if not replaced:
        out += ["-s", addon_path]

    def _cleanup():
        try:
            shutil.rmtree(tmp, ignore_errors=True)
        except Exception:
            pass

    atexit.register(_cleanup)
    return out, tmp


# When frozen, bundled packages live in _MEIPASS; make sure imports resolve.
if getattr(sys, "frozen", False):
    bundle_dir = getattr(sys, "_MEIPASS", os.path.dirname(os.path.abspath(__file__)))
    sys.path.insert(0, bundle_dir)

    # Point Python's SSL machinery at the bundled CA bundle (certifi). Without
    # this, requests/urllib3 in the frozen engine fail every outbound HTTPS
    # call with CERTIFICATE_VERIFY_FAILED "unable to get local issuer
    # certificate" (e.g. spaCy model downloads, tldextract PSL fetches).
    _cacert = os.path.join(bundle_dir, "certifi", "cacert.pem")
    if os.path.exists(_cacert):
        os.environ.setdefault("SSL_CERT_FILE", _cacert)
        os.environ.setdefault("SSL_CERT_DIR", "")

from mitmproxy.tools.main import mitmdump  # noqa: E402

if __name__ == "__main__":
    argv = sys.argv[1:]
    argv, _ = _prepare_addon(argv)
    sys.exit(mitmdump(argv))
